name: Check and run
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install lua
        run: |
          sudo apt-get update -qq &&
          sudo apt-get install -qq --no-install-recommends lua5.3 lua-busted lua-check
      - name: Check lua files
        run: bin/check-lua-scripts.sh
      - name: Run tests
        env:
          LUA_PATH: "lua/?.lua;;"
        run: bin/run-tests.sh

